import Square from "@/components/ChessBoard/Square/Square.vue";

export default {
  name: "ChessBoard",
  components: {
    Square,
  },
  props: {},
  data() {
    return {
      dummyData: [
        [
          {
            x: 0,
            y: 0,
            isSelected: false,
            isEmpty: false,
            pieceName: "rook",
            pieceColor: "black",
            possibleMoves: [
              [0, 1],
              [0, 2],
            ],
          },
          {
            x: 1,
            y: 0,
            isSelected: false,
            isEmpty: false,
            pieceName: "knight",
            pieceColor: "black",
            possibleMoves: [
              [3, 1],
              [0, 2],
            ],
          },
          {
            x: 2,
            y: 0,
            isSelected: false,
            isEmpty: false,
            pieceName: "bishop",
            pieceColor: "black",
            possibleMoves: [
              [3, 1],
              [6, 4],
              [4, 2],
              [5, 3],
              [7, 5],
            ],
          },
          {
            x: 3,
            y: 0,
            isSelected: false,
            isEmpty: false,
            pieceName: "queen",
            pieceColor: "black",
            possibleMoves: [
              [3, 1],
              [3, 2],
              [1, 2],
              [2, 1],
            ],
          },
          {
            x: 4,
            y: 0,
            isSelected: false,
            isEmpty: false,
            pieceName: "king",
            pieceColor: "black",
            possibleMoves: [[3, 1]],
          },
          {
            x: 5,
            y: 0,
            isSelected: false,
            isEmpty: false,
            pieceName: "bishop",
            pieceColor: "black",
            possibleMoves: [],
          },
          {
            x: 6,
            y: 0,
            isSelected: false,
            isEmpty: false,
            pieceName: "knight",
            pieceColor: "black",
            possibleMoves: [
              [7, 2],
              [5, 2],
            ],
          },
          {
            x: 7,
            y: 0,
            isSelected: false,
            isEmpty: false,
            pieceName: "rook",
            pieceColor: "black",
            possibleMoves: [],
          },
        ],
        [
          {
            x: 0,
            y: 1,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 1,
            y: 1,
            isSelected: false,
            isEmpty: false,
            pieceName: "pawn",
            pieceColor: "black",
            possibleMoves: [
              [1, 2],
              [1, 3],
            ],
          },
          {
            x: 2,
            y: 1,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 3,
            y: 1,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 4,
            y: 1,
            isSelected: false,
            isEmpty: false,
            pieceName: "pawn",
            pieceColor: "black",
            possibleMoves: [
              [4, 2],
              [4, 3],
            ],
          },
          {
            x: 5,
            y: 1,
            isSelected: false,
            isEmpty: false,
            pieceName: "pawn",
            pieceColor: "black",
            possibleMoves: [
              [5, 3],
              [5, 2],
            ],
          },
          {
            x: 6,
            y: 1,
            isSelected: false,
            isEmpty: false,
            pieceName: "pawn",
            pieceColor: "black",
            possibleMoves: [
              [6, 2],
              [6, 3],
            ],
          },
          {
            x: 7,
            y: 1,
            isSelected: false,
            isEmpty: false,
            pieceName: "pawn",
            pieceColor: "black",
            possibleMoves: [
              [7, 2],
              [7, 3],
            ],
          },
        ],
        [
          {
            x: 0,
            y: 2,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 1,
            y: 2,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 2,
            y: 2,
            isSelected: false,
            isEmpty: false,
            pieceName: "pawn",
            pieceColor: "black",
            possibleMoves: [[2, 3]],
          },
          {
            x: 3,
            y: 2,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 4,
            y: 2,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 5,
            y: 2,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 6,
            y: 2,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 7,
            y: 2,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
        ],
        [
          {
            x: 0,
            y: 3,
            isSelected: false,
            isEmpty: false,
            pieceName: "pawn",
            pieceColor: "black",
            possibleMoves: [[0, 4]],
          },
          {
            x: 1,
            y: 3,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 2,
            y: 3,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 3,
            y: 3,
            isSelected: false,
            isEmpty: false,
            pieceName: "pawn",
            pieceColor: "black",
            possibleMoves: [
              [2, 4],
              [3, 4],
            ],
          },
          {
            x: 4,
            y: 3,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 5,
            y: 3,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 6,
            y: 3,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 7,
            y: 3,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
        ],
        [
          {
            x: 0,
            y: 4,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 1,
            y: 4,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 2,
            y: 4,
            isSelected: false,
            isEmpty: false,
            pieceName: "pawn",
            pieceColor: "white",
            possibleMoves: [
              [2, 3],
              [3, 3],
            ],
          },
          {
            x: 3,
            y: 4,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 4,
            y: 4,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 5,
            y: 4,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 6,
            y: 4,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 7,
            y: 4,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
        ],
        [
          {
            x: 0,
            y: 5,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 1,
            y: 5,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 2,
            y: 5,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 3,
            y: 5,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 4,
            y: 5,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 5,
            y: 5,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 6,
            y: 5,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 7,
            y: 5,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
        ],
        [
          {
            x: 0,
            y: 6,
            isSelected: false,
            isEmpty: false,
            pieceName: "pawn",
            pieceColor: "white",
            possibleMoves: [
              [0, 4],
              [0, 5],
            ],
          },
          {
            x: 1,
            y: 6,
            isSelected: false,
            isEmpty: false,
            pieceName: "pawn",
            pieceColor: "white",
            possibleMoves: [
              [1, 4],
              [1, 5],
            ],
          },
          {
            x: 2,
            y: 6,
            isSelected: false,
            isEmpty: true,
            pieceName: "",
            pieceColor: "",
            possibleMoves: [],
          },
          {
            x: 3,
            y: 6,
            isSelected: false,
            isEmpty: false,
            pieceName: "pawn",
            pieceColor: "white",
            possibleMoves: [
              [3, 4],
              [3, 5],
            ],
          },
          {
            x: 4,
            y: 6,
            isSelected: false,
            isEmpty: false,
            pieceName: "pawn",
            pieceColor: "white",
            possibleMoves: [
              [4, 4],
              [4, 5],
            ],
          },
          {
            x: 5,
            y: 6,
            isSelected: false,
            isEmpty: false,
            pieceName: "pawn",
            pieceColor: "white",
            possibleMoves: [
              [5, 4],
              [5, 5],
            ],
          },
          {
            x: 6,
            y: 6,
            isSelected: false,
            isEmpty: false,
            pieceName: "pawn",
            pieceColor: "white",
            possibleMoves: [
              [6, 4],
              [6, 5],
            ],
          },
          {
            x: 7,
            y: 6,
            isSelected: false,
            isEmpty: false,
            pieceName: "pawn",
            pieceColor: "white",
            possibleMoves: [
              [7, 4],
              [7, 5],
            ],
          },
        ],
        [
          {
            x: 0,
            y: 7,
            isSelected: false,
            isEmpty: false,
            pieceName: "rook",
            pieceColor: "white",
            possibleMoves: [],
          },
          {
            x: 1,
            y: 7,
            isSelected: false,
            isEmpty: false,
            pieceName: "knight",
            pieceColor: "white",
            possibleMoves: [
              [2, 5],
              [0, 5],
            ],
          },
          {
            x: 2,
            y: 7,
            isSelected: false,
            isEmpty: false,
            pieceName: "bishop",
            pieceColor: "white",
            possibleMoves: [],
          },
          {
            x: 3,
            y: 7,
            isSelected: false,
            isEmpty: false,
            pieceName: "queen",
            pieceColor: "white",
            possibleMoves: [
              [2, 6],
              [0, 4],
              [1, 5],
            ],
          },
          {
            x: 4,
            y: 7,
            isSelected: false,
            isEmpty: false,
            pieceName: "king",
            pieceColor: "white",
            possibleMoves: [],
          },
          {
            x: 5,
            y: 7,
            isSelected: false,
            isEmpty: false,
            pieceName: "bishop",
            pieceColor: "white",
            possibleMoves: [],
          },
          {
            x: 6,
            y: 7,
            isSelected: false,
            isEmpty: false,
            pieceName: "knight",
            pieceColor: "white",
            possibleMoves: [
              [7, 5],
              [5, 5],
            ],
          },
          {
            x: 7,
            y: 7,
            isSelected: false,
            isEmpty: false,
            pieceName: "rook",
            pieceColor: "white",
            possibleMoves: [],
          },
        ],
      ],
    };
  },
};
